INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:apscheduler.scheduler:Scheduler started
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:No jobs; waiting until a job is added
INFO:apscheduler.scheduler:Added job "checkLights" to job store "default"
INFO:apscheduler.scheduler:Added job "activatePump" to job store "default"
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2021-03-09 23:42:56.408437+01:00 (in 4.999171 seconds)
INFO:roboLog:System started. System time is: 23:42
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2021-03-09 23:42:56.408437+01:00 (in 4.998637 seconds)
INFO:roboLog:Current program: {'progID': '004', 'progName': 'Growth - quiet hours, low watering, more red light', 'pumpStartEvery': 7200, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '21:00', 'lightBrightness': 255, 'RGB': '255 150 150', 'lightsON': '06:00', 'lightsOFF': '23:00', 'progDescription': 'Program seeds to small plants, less water.'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
DEBUG:apscheduler.scheduler:Looking for jobs to run
INFO:apscheduler.executors.default:Running job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-09 23:42:56 CET)" (scheduled at 2021-03-09 23:42:56.408437+01:00)
DEBUG:apscheduler.scheduler:Next wakeup is due at 2021-03-09 23:43:01.408437+01:00 (in 4.998878 seconds)
INFO:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-09 23:43:01 CET)" executed successfully
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2021-03-09 23:43:06.408437+01:00 (in 4.996446 seconds)
INFO:apscheduler.executors.default:Running job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-09 23:43:06 CET)" (scheduled at 2021-03-09 23:43:01.408437+01:00)
INFO:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-09 23:43:06 CET)" executed successfully
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2021-03-09 23:43:11.408437+01:00 (in 4.998275 seconds)
INFO:apscheduler.executors.default:Running job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-09 23:43:11 CET)" (scheduled at 2021-03-09 23:43:06.408437+01:00)
INFO:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-09 23:43:11 CET)" executed successfully
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2021-03-09 23:43:16.408437+01:00 (in 4.998142 seconds)
INFO:apscheduler.executors.default:Running job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-09 23:43:16 CET)" (scheduled at 2021-03-09 23:43:11.408437+01:00)
INFO:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-09 23:43:16 CET)" executed successfully
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2021-03-09 23:43:21.408437+01:00 (in 4.999114 seconds)
INFO:apscheduler.executors.default:Running job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-09 23:43:21 CET)" (scheduled at 2021-03-09 23:43:16.408437+01:00)
INFO:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-09 23:43:21 CET)" executed successfully
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:55
INFO:roboLog:Current program: {'progID': '004', 'progName': 'Growth - quiet hours, low watering, more red light', 'pumpStartEvery': 7200, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '21:00', 'lightBrightness': 255, 'RGB': '255 150 150', 'lightsON': '06:00', 'lightsOFF': '23:00', 'progDescription': 'Program seeds to small plants, less water.'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 18:30
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Info from Arduino: Brightness set to: 255 (100%)
INFO:roboLog:RGB set to 255 150 255
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 18:30:32 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 147, in checkLights
    if dataJSON["RGB"] != currentProgram["RGB"]:
KeyError: 'RGB'
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
INFO:roboLog:Info from Arduino: LED set to RGB: 0 0 255
INFO:roboLog:Info from Arduino: Pump started for: 10 seconds
INFO:roboLog:Info from Arduino: Pump stopped
INFO:roboLog:Info from Arduino: LED set to RGB: 0 0 255 
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
INFO:roboLog:Info from Arduino: LED set to RGB: 0 0 255
INFO:roboLog:Info from Arduino: Pump started for: 10 seconds
INFO:roboLog:Info from Arduino: Pump stopped
INFO:roboLog:Info from Arduino: LED set to RGB: 0 0 255 
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
INFO:roboLog:Info from Arduino: LED set to RGB: 0 0 255
INFO:roboLog:Info from Arduino: Pump started for: 10 seconds
INFO:roboLog:Info from Arduino: Pump stopped
INFO:roboLog:Info from Arduino: LED set to RGB: 0 0 255 
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
INFO:roboLog:Lights set to 255
WARNING:roboLog:Received non-JSON from Arduino: bytearray(b''type':'T','pumpON':0,'RGB':'255 150 255','brightness':255}\r\n')Extra data: line 1 column 7 (char 6)
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:49:32 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:49:37 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:49:42 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:49:47 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:49:52 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:49:57 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:50:02 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:50:07 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:50:12 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:50:17 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:50:22 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:50:27 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:50:32 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:50:37 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:50:42 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:50:47 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:50:52 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:50:57 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:51:02 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:51:07 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:51:12 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:51:17 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-12 23:51:22 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 156, in checkLights
    arduinoCommand("setBrightness 0")
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 89, in arduinoCommand
    serial.Serial(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 16:07
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Info from Arduino: Brightness set to: 255 (100%)
INFO:roboLog:RGB set to 255 150 255
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-13 16:07:25 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 147, in checkLights
    if dataJSON["RGB"] != currentProgram["RGB"]:
KeyError: 'RGB'
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
ERROR:blueprints:Exception on /profile [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 26, in profile
    return render_template("profile.html")
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/base.html", line 21, in top-level template code
    <a href="{{ url_for('main.index') }}" class="navbar-item">
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.index'. Did you mean 'auth_bp.index' instead?
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 16:09
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /profile [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 26, in profile
    return render_template("profile.html")
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/base.html", line 27, in top-level template code
    <a href="{{ url_for('auth_bp.login') }}" class="navbar-item">
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth_bp.login'. Did you mean 'auth_bp.index' instead?
INFO:roboLog:Info from Arduino: Brightness set to: 255 (100%)
INFO:roboLog:RGB set to 255 150 255
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 16:11
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /profile [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 26, in profile
    return render_template("profile.html")
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/base.html", line 33, in top-level template code
    <a href="{{ url_for('auth_bp.logout') }}" class="navbar-item">
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth_bp.logout'. Did you mean 'auth_bp.login' instead?
INFO:roboLog:Info from Arduino: Brightness set to: 255 (100%)
INFO:roboLog:RGB set to 255 150 255
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-13 16:12:03 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 147, in checkLights
    if dataJSON["RGB"] != currentProgram["RGB"]:
KeyError: 'RGB'
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 16:13
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /profile [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 26, in profile
    return render_template("profile.html")
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/base.html", line 33, in top-level template code
    <!-- <a href="{{ url_for('auth_bp.logout') }}" class="navbar-item">
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth_bp.logout'. Did you mean 'auth_bp.login' instead?
INFO:roboLog:Info from Arduino: Brightness set to: 255 (100%)
INFO:roboLog:RGB set to 255 150 255
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-13 16:13:26 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 147, in checkLights
    if dataJSON["RGB"] != currentProgram["RGB"]:
KeyError: 'RGB'
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 16:15
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Info from Arduino: Brightness set to: 255 (100%)
INFO:roboLog:RGB set to 255 150 255
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 16:36
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Info from Arduino: Brightness set to: 255 (100%)
INFO:roboLog:RGB set to 255 150 255
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-13 16:37:07 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 147, in checkLights
    if dataJSON["RGB"] != currentProgram["RGB"]:
KeyError: 'RGB'
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 16:38
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Info from Arduino: Brightness set to: 255 (100%)
INFO:roboLog:RGB set to 255 150 255
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 16:38
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Info from Arduino: Brightness set to: 255 (100%)
INFO:roboLog:RGB set to 255 150 255
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 17:33
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Info from Arduino: Brightness set to: 255 (100%)
INFO:roboLog:RGB set to 255 150 255
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
ERROR:blueprints:Exception on /signup [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 38, in signup
    return render_template(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 136, in render_template
    ctx.app.update_template_context(context)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 838, in update_template_context
    context.update(func())
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 379, in _user_context_processor
    return dict(current_user=_get_user())
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 302, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 18:25
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /signup [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 38, in signup
    return render_template(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 136, in render_template
    ctx.app.update_template_context(context)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 838, in update_template_context
    context.update(func())
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 379, in _user_context_processor
    return dict(current_user=_get_user())
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 302, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
INFO:roboLog:Info from Arduino: Brightness set to: 255 (100%)
INFO:roboLog:RGB set to 255 150 255
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-13 18:25:35 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 147, in checkLights
    if dataJSON["RGB"] != currentProgram["RGB"]:
KeyError: 'RGB'
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 56, in login
    if current_user.is_authenticated:
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 302, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 18:33
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 56, in login
    if current_user.is_authenticated:
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 302, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
INFO:roboLog:Info from Arduino: Brightness set to: 255 (100%)
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 18:48
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 56, in login
    if current_user.is_authenticated:
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 302, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
INFO:roboLog:Info from Arduino: Brightness set to: 255 (100%)
INFO:roboLog:RGB set to 255 150 255
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-13 18:48:45 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 147, in checkLights
    if dataJSON["RGB"] != currentProgram["RGB"]:
KeyError: 'RGB'
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 56, in login
    if current_user.is_authenticated:
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 302, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 18:50
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 56, in login
    if current_user.is_authenticated:
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 302, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 56, in login
    if current_user.is_authenticated:
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 302, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
INFO:roboLog:Info from Arduino: Brightness set to: 255 (100%)
INFO:roboLog:RGB set to 255 150 255
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-13 18:50:45 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 147, in checkLights
    if dataJSON["RGB"] != currentProgram["RGB"]:
KeyError: 'RGB'
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 18:51
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 56, in login
    if current_user.is_authenticated:
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 302, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
INFO:roboLog:Info from Arduino: Brightness set to: 255 (100%)
INFO:roboLog:RGB set to 255 150 255
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-13 18:51:53 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 147, in checkLights
    if dataJSON["RGB"] != currentProgram["RGB"]:
KeyError: 'RGB'
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 18:52
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 56, in login
    if current_user.is_authenticated:
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 302, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
INFO:roboLog:Info from Arduino: Brightness set to: 255 (100%)
INFO:roboLog:RGB set to 255 150 255
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 18:54
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 71, in login
    if current_user.is_authenticated:
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 302, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
INFO:roboLog:Info from Arduino: Brightness set to: 255 (100%)
INFO:roboLog:RGB set to 255 150 255
ERROR:apscheduler.executors.default:Job "checkLights (trigger: interval[0:00:05], next run at: 2021-03-13 18:54:21 CET)" raised an exception
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/threads.py", line 147, in checkLights
    if dataJSON["RGB"] != currentProgram["RGB"]:
KeyError: 'RGB'
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 19:01
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 97, in login
    if current_user.is_authenticated:
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 302, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
INFO:roboLog:Info from Arduino: Brightness set to: 255 (100%)
INFO:roboLog:RGB set to 255 150 255
INFO:roboLog:Info from Arduino: LED set to RGB: 255 150 255 
INFO:roboLog:Lights set to 255
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 22:34
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 22:36
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 22:46
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 22:50
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /profile [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 271, in decorated_view
    return current_app.login_manager.unauthorized()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 174, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 120, in login_url
    base = expand_login_view(login_view)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 97, in expand_login_view
    return url_for(login_view)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth.login'. Did you mean 'auth_bp.index' instead?
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:02
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /profile [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 271, in decorated_view
    return current_app.login_manager.unauthorized()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 174, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 120, in login_url
    base = expand_login_view(login_view)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 97, in expand_login_view
    return url_for(login_view)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth_bp.login'. Did you mean 'auth_bp.index' instead?
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:03
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:12
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /profile [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 271, in decorated_view
    return current_app.login_manager.unauthorized()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 174, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 120, in login_url
    base = expand_login_view(login_view)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 97, in expand_login_view
    return url_for(login_view)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth_bp.login'. Did you mean 'auth_bp.index' instead?
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:16
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 19, in index
    return render_template("index.html")
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/base.html", line 27, in top-level template code
    <a href="{{ url_for('auth_bp.login') }}" class="navbar-item">
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth_bp.login'. Did you mean 'auth_bp.index' instead?
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:24
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 19, in index
    return render_template("index.html")
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/base.html", line 27, in top-level template code
    <a href="{{ url_for('auth_bp.login') }}" class="navbar-item">
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth_bp.login'. Did you mean 'auth_bp.index' instead?
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:24
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 19, in login
    return render_template("index.html")
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/base.html", line 21, in top-level template code
    <a href="{{ url_for('auth_bp.index') }}" class="navbar-item">
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth_bp.index'. Did you mean 'auth_bp.login' instead?
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:25
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 19, in login
    return render_template("index.html")
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/base.html", line 21, in top-level template code
    <a href="{{ url_for('auth_bp.index') }}" class="navbar-item">
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth_bp.index'. Did you mean 'auth_bp.login' instead?
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 19, in login
    return render_template("index.html")
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/base.html", line 21, in top-level template code
    <a href="{{ url_for('auth_bp.index') }}" class="navbar-item">
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth_bp.index'. Did you mean 'auth_bp.login' instead?
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 19, in login
    return render_template("index.html")
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/base.html", line 21, in top-level template code
    <a href="{{ url_for('auth_bp.index') }}" class="navbar-item">
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth_bp.index'. Did you mean 'auth_bp.login' instead?
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 19, in login
    return render_template("index.html")
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/base.html", line 21, in top-level template code
    <a href="{{ url_for('auth_bp.index') }}" class="navbar-item">
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth_bp.index'. Did you mean 'auth_bp.login' instead?
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:25
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 19, in login
    return render_template("index.html")
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/base.html", line 21, in top-level template code
    <a href="{{ url_for('auth_bp.index') }}" class="navbar-item">
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth_bp.index'. Did you mean 'auth_bp.login' instead?
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:27
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 19, in login
    return render_template("index.html")
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/base.html", line 30, in top-level template code
    <a href="{{ url_for('auth_bp.signup') }}" class="navbar-item">
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth_bp.signup'. Did you mean 'auth_bp.login' instead?
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:27
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:29
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /login [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 19, in login
    return render_template("login.j2.html")
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/login.j2.html", line 59, in template
    <a href="{{ url_for('auth_bp.signup') }}">Sign up.</a>
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
ERROR:blueprints:Exception on /signup [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 24, in signup
    return render_template("signup.j2.html")
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/signup.j2.html", line 1, in top-level template code
    {% extends "layout.jinja2" %}
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/templates/layout.jinja2", line 11, in top-level template code
    {% block content %}{% endblock %}
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/signup.j2.html", line 29, in block "content"
    {{ form.csrf_token }}
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:30
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:37
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /signup [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 24, in signup
    return render_template("signup.html")
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: signup.html
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:37
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /signup [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 24, in signup
    return render_template("signup.j2.html")
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/signup.j2.html", line 1, in top-level template code
    {% extends "layout.jinja2" %}
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/templates/layout.jinja2", line 11, in top-level template code
    {% block content %}{% endblock %}
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/signup.j2.html", line 29, in block "content"
    {{ form.csrf_token }}
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:43
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /signup [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 24, in signup
    return render_template("signup.j2.html")
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/signup.j2.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/templates/base.html", line 24, in top-level template code
    <a href="{{ url_for('auth_bp.profile') }}" class="navbar-item">
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth_bp.profile'. Did you mean 'auth_bp.login' instead?
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:44
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:47
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /signup [POST]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 45, in signup_post
    return redirect(url_for("auth.signup"))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth.signup'. Did you mean 'auth_bp.signup' instead?
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:48
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /signup [POST]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 51, in signup_post
    password=generate_password_hash(password, method="sha256"),
NameError: name 'generate_password_hash' is not defined
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:50
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:56
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 23:59
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 00:01
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 00:13
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 00:25
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
ERROR:blueprints:Exception on /logout [GET]
Traceback (most recent call last):
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/paolo/NAS/Software/roboGarden/server/blueprints/auth/auth.py", line 48, in logout
    return redirect(url_for("auth_bp.index"))
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/paolo/NAS/Software/roboGarden/server/.venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth_bp.index'. Did you mean 'auth_bp.login' instead?
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 00:26
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 00:29
INFO:roboLog:Current program: {'progID': '001', 'progName': 'Default - quiet hours', 'pumpStartEvery': 1800, 'pumpRunTime': 15, 'pumpON': '08:00', 'pumpOFF': '22:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '22:00', 'progDescription': 'Default program, lights and pump are off during quiet hours. Medium watering'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:New plant planted: Babyleaf Salad ID:002 in 00-08-01
INFO:roboLog:Time to harvest computed.  2 plants should be ready!
INFO:roboLog:New program: {'progID': '004', 'progName': 'Harvest - quiet hours, high watering', 'pumpStartEvery': 1800, 'pumpRunTime': 25, 'pumpON': '08:00', 'pumpOFF': '23:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '23:00', 'progDescription': 'Program for plant maturity, higher water and more light hours'}
INFO:roboLog:Info from Arduino: LED set to RGB: 0 0 255
INFO:roboLog:Info from Arduino: Pump started for: 10 seconds
INFO:roboLog:Info from Arduino: Pump stopped
INFO:roboLog:Info from Arduino: LED set to RGB: 0 0 255 
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 00:42
INFO:roboLog:Current program: {'progID': '004', 'progName': 'Harvest - quiet hours, high watering', 'pumpStartEvery': 1800, 'pumpRunTime': 25, 'pumpON': '08:00', 'pumpOFF': '23:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '23:00', 'progDescription': 'Program for plant maturity, higher water and more light hours'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 00:53
INFO:roboLog:Current program: {'progID': '004', 'progName': 'Harvest - quiet hours, high watering', 'pumpStartEvery': 1800, 'pumpRunTime': 25, 'pumpON': '08:00', 'pumpOFF': '23:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '23:00', 'progDescription': 'Program for plant maturity, higher water and more light hours'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 00:55
INFO:roboLog:Current program: {'progID': '004', 'progName': 'Harvest - quiet hours, high watering', 'pumpStartEvery': 1800, 'pumpRunTime': 25, 'pumpON': '08:00', 'pumpOFF': '23:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '23:00', 'progDescription': 'Program for plant maturity, higher water and more light hours'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 00:55
INFO:roboLog:Current program: {'progID': '004', 'progName': 'Harvest - quiet hours, high watering', 'pumpStartEvery': 1800, 'pumpRunTime': 25, 'pumpON': '08:00', 'pumpOFF': '23:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '23:00', 'progDescription': 'Program for plant maturity, higher water and more light hours'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 00:57
INFO:roboLog:Current program: {'progID': '004', 'progName': 'Harvest - quiet hours, high watering', 'pumpStartEvery': 1800, 'pumpRunTime': 25, 'pumpON': '08:00', 'pumpOFF': '23:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '23:00', 'progDescription': 'Program for plant maturity, higher water and more light hours'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
INFO:roboLog:Serial interface configured on /dev/ttyACM0@115200 Pyserisal version: 3.5
INFO:roboLog:System started. System time is: 00:58
INFO:roboLog:Current program: {'progID': '004', 'progName': 'Harvest - quiet hours, high watering', 'pumpStartEvery': 1800, 'pumpRunTime': 25, 'pumpON': '08:00', 'pumpOFF': '23:00', 'lightBrightness': 255, 'RGB': '255 150 255', 'lightsON': '06:00', 'lightsOFF': '23:00', 'progDescription': 'Program for plant maturity, higher water and more light hours'}
INFO:roboLog:Background jobs: [<Job (id=checkL name=checkLights)>, <Job (id=checkP name=activatePump)>]
